#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : plasma-thunderbolt
Version  : 5.19.2
Release  : 1
URL      : https://download.kde.org/stable/plasma/5.19.2/plasma-thunderbolt-5.19.2.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.19.2/plasma-thunderbolt-5.19.2.tar.xz
Source1  : https://download.kde.org/stable/plasma/5.19.2/plasma-thunderbolt-5.19.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: plasma-thunderbolt-data = %{version}-%{release}
Requires: plasma-thunderbolt-lib = %{version}-%{release}
Requires: plasma-thunderbolt-license = %{version}-%{release}
Requires: plasma-thunderbolt-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kcmutils-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdeclarative-dev
BuildRequires : ki18n-dev
BuildRequires : knotifications-dev
BuildRequires : qtbase-dev
BuildRequires : qtdeclarative-dev

%description
# Plasma Thunderbolt
This repository contains a Plasma Sytem Settings module and a KDED module to
handle authorization of Thunderbolt devices connected to the computer. There's
also a shared library (libkbolt) that implements common interface between the
modules and the system-wide bolt daemon, which does the actual hard work of
talking to the kernel.

%package data
Summary: data components for the plasma-thunderbolt package.
Group: Data

%description data
data components for the plasma-thunderbolt package.


%package dev
Summary: dev components for the plasma-thunderbolt package.
Group: Development
Requires: plasma-thunderbolt-lib = %{version}-%{release}
Requires: plasma-thunderbolt-data = %{version}-%{release}
Provides: plasma-thunderbolt-devel = %{version}-%{release}
Requires: plasma-thunderbolt = %{version}-%{release}

%description dev
dev components for the plasma-thunderbolt package.


%package lib
Summary: lib components for the plasma-thunderbolt package.
Group: Libraries
Requires: plasma-thunderbolt-data = %{version}-%{release}
Requires: plasma-thunderbolt-license = %{version}-%{release}

%description lib
lib components for the plasma-thunderbolt package.


%package license
Summary: license components for the plasma-thunderbolt package.
Group: Default

%description license
license components for the plasma-thunderbolt package.


%package locales
Summary: locales components for the plasma-thunderbolt package.
Group: Default

%description locales
locales components for the plasma-thunderbolt package.


%prep
%setup -q -n plasma-thunderbolt-5.19.2
cd %{_builddir}/plasma-thunderbolt-5.19.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592944443
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1592944443
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-thunderbolt
cp %{_builddir}/plasma-thunderbolt-5.19.2/COPYING %{buildroot}/usr/share/package-licenses/plasma-thunderbolt/7c203dee3a03037da436df03c4b25b659c073976
pushd clr-build
%make_install
popd
%find_lang kcm_bolt
%find_lang kded_bolt

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/knotifications5/kded_bolt.notifyrc
/usr/share/kpackage/kcms/kcm_bolt/contents/ui/DeviceList.qml
/usr/share/kpackage/kcms/kcm_bolt/contents/ui/DeviceView.qml
/usr/share/kpackage/kcms/kcm_bolt/contents/ui/main.qml
/usr/share/kpackage/kcms/kcm_bolt/contents/ui/utils.js
/usr/share/kpackage/kcms/kcm_bolt/metadata.desktop
/usr/share/kpackage/kcms/kcm_bolt/metadata.json
/usr/share/kservices5/kcm_bolt.desktop

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkbolt.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kcms/kcm_bolt.so
/usr/lib64/qt5/plugins/kf5/kded/kded_bolt.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-thunderbolt/7c203dee3a03037da436df03c4b25b659c073976

%files locales -f kcm_bolt.lang -f kded_bolt.lang
%defattr(-,root,root,-)

